### ISSUE TITLE
During shipment the phase indicator is placed on the battle spot instead of shipment.

### ISSUE THREAD

**Issue by SmartTrigger** [jamesmkinder/DuneBot#101]

**Comment by jamesmkinder** [comment]
Cannot reproduce issue

**Comment by TomHayosh** [comment]
The phases as implemented now are really endpoints, not the spans between endpoints. There is a startShipmentPhase endpoint that then immediately advances the phase to the startBattlePhase endpoint.

We could add finish endpoints to every phase, or it might be possible to turn everything into spans. Some phases would still need multiple subPhase spans.
