### ISSUE TITLE
During Storm Phase the player holding FA should only be @ tagged if they can actually play it.

### ISSUE THREAD

**Issue by SmartTrigger** [jamesmkinder/DuneBot#234]
They'd need forces in either:

- Shield Wall
- False Wall East
- The Minor Erg
- Pasty Mesa
- Gara Kulon
- Sihaya Ridge
- Hole in the Rock
- Imperial Basin

**Comment by TomHayosh** [comment]
Fixed with https://github.com/jamesmkinder/DuneBot/pull/244
